defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-25-alpha
  environment:
    JVM_OPTS: -Xmx3200m

version: 2
jobs:
  download_dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  test_lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Lint
          command: ./gradlew lint
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  test_checkstyle:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run CheckStyle
          command: ./gradlew checkstyle
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  test_findbugs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run FindBugs
          command: ./gradlew findbugs
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  test_pmd:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run PMD
          command: ./gradlew pmd
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  unit_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Unit Tests
          command: ./gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  build_apk:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - deploy:
          name: Deploy APK.
          command: |
            bash ./scripts/deploy-hockey.sh
            bash ./scripts/deploy-fabric.sh

workflows:
  version: 2
  integrate:
    jobs:
      - download_dependencies
      - test_lint:
          requires:
            - download_dependencies
      - test_checkstyle:
          requires:
            - download_dependencies
      - test_findbugs:
          requires:
            - download_dependencies
      - test_pmd:
          requires:
            - download_dependencies
      - unit_tests:
          requires:
            - download_dependencies
      - build_apk:
          requires:
            - test_lint
            - test_checkstyle
            - test_findbugs
            - test_pmd
            - unit_tests
      - deploy:
          requires:
            - build_apk
          filters:
            branches:
              only:
                - master
